# Generated by Django 4.1.3 on 2022-11-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'banner',
            },
        ),
        migrations.CreateModel(
            name='CardFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=50)),
                ('alt', models.CharField(max_length=50)),
                ('creci', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'cardfront',
            },
        ),
    ]
