# Generated by Django 4.1.4 on 2022-12-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
